const express = require('express')
const favicon = require('serve-favicon')
const path = require('path')

const app = express()
app.use(express.static(path.join(__dirname, 'css')))
app.use(express.static(path.join(__dirname, 'img')))
app.use(express.static(path.join(__dirname, 'js')))
app.use(favicon(path.join(__dirname, 'img/favicon.ico')))
app.get('/', function (req, res) { res.sendFile(path.join(__dirname, 'index.html')) })
app.listen(3000, () => console.log('App listening on port 3000!'))